title: '버그 제목'
labels: ['환경세팅', 'API', '기타']
body:
  - type: markdown
    attributes:
      value: |
        ### JIRA 이슈 번호 ex) NABI-1
  - type: input
    id: jira-id
    attributes:
      label: 이슈 번호
      description: JIRA 이슈 번호를 작성해주세요
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### :beetle: Bug Report
        1시간 이상 버그가 해결되지 않는 경우 작성해주세요
  - type: textarea
    id: content
    attributes:
      label: 현재 상황과 버그 내용을 작성해주세요
      description: '현재 상황과 버그 내용을 자세하게 작성해주세요'
      placeholder: 예시) 물건 상세 페이지에서 거래 제안하기 버튼을 클릭했더니 화면에 모달이 뜨지 않는 에러가 발생했다.
      render: bash
    validations:
      required: true
  - type: textarea
    id: cause
    attributes:
      label: 예상 원인
      description: '문제가 발생한 원인을 예상하여 작성해주세요'
      render: bash
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: 이슈와 관련된 현재 코드 (선택)
      description: '버그와 관련된 현재 코드를 첨부해주세요'
      render: shell
    validations:
      required: false
  - type: textarea
    id: image
    attributes:
      label: 버그와 관련된 Log (선택)
      description: '버그와 관련된 Log를 첨부해주세요'
      render: shell
    validations:
      required: false
