name: 'Chromatic'
on:
  push:
    branches: ['develop']

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          npm install -g pnpm

      - name: Install Dependency
        run: pnpm install

      - name: Publish to Chromatic
        uses: chromaui/action@v1

        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
